name: remote deploy test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GIT_SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }} # ssh_config; optional
          if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)
      - run: |
          ssh -vvv mila exit
        name: ssh check

      - run: |
          set -e
          set -x

          export GIT_MAIL=${{ secrets.GIT_MAIL }}
          export GIT_NAME=${{ secrets.GIT_NAME }}
          export TERM=xterm
          export WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}

          git config --global user.email "$GIT_MAIL"
          git config --global user.name "$GIT_NAME"

          # https://stackoverflow.com/questions/7772190/passing-ssh-options-to-git-clone/28527476#28527476
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:ministry-of-silly-code/examples.git examples_remote

          python3 -m venv venv
          source venv/bin/activate

          cd examples_remote
          pip install -r requirements.txt
          export BUDDY_HOST="mila"
          eval `ssh-agent -s`
          echo "GA-run-remote" | python mnist_classifier.py
